import type { BuyerId, Category, Product, Order } from './types';

export const DEMO_DATE = '2026-09-15';
export const buyers: Record<BuyerId, string> = { A: '林同学', B: '陈同学' };
const items: Array<[string, string, Category, string, number, number, string[], string, string]> = [
  [
    'p01',
    'AirBeat Pro 降噪耳机',
    '耳机',
    'AIRBEAT',
    299,
    28,
    ['主动降噪', '蓝牙 5.3', '续航 32 小时'],
    '通勤与在线会议都从容，轻巧入耳，清晰通话。',
    'blue',
  ],
  [
    'p02',
    'Studio One 头戴耳机',
    '耳机',
    'STUDIO',
    499,
    12,
    ['40mm 单元', '双设备连接', '续航 45 小时'],
    '更沉浸的声音，柔软耳罩适合长时间聆听。',
    'purple',
  ],
  [
    'p03',
    'AirBeat Lite 无线耳机',
    '耳机',
    'AIRBEAT',
    159,
    0,
    ['半入耳', '蓝牙 5.2', '续航 24 小时'],
    '轻量佩戴，适合日常听歌与通话。',
    'mint',
  ],
  [
    'p04',
    'Sport Loop 运动耳机',
    '耳机',
    'SPORT',
    239,
    36,
    ['稳固耳挂', 'IPX5', '续航 28 小时'],
    '运动场景的稳固佩戴选择。',
    'orange',
  ],
  [
    'p05',
    'PowerMini 65W 氮化镓充电器',
    '充电器',
    'POWERMINI',
    129,
    45,
    ['65W PD', '双 USB-C', '折叠插脚'],
    '桌面和差旅的一块轻量电源。',
    'blue',
  ],
  [
    'p06',
    'PowerDesk 100W 桌面充电器',
    '充电器',
    'POWERDESK',
    259,
    17,
    ['100W PD', '三接口', '智能功率分配'],
    '为桌面多设备提供集中供电。',
    'purple',
  ],
  [
    'p07',
    'Pocket 30W 迷你充电器',
    '充电器',
    'POCKET',
    69,
    60,
    ['30W PD', '单 USB-C', '紧凑机身'],
    '为支持 PD 的移动设备提供便携充电。',
    'mint',
  ],
  [
    'p08',
    'PowerTravel 140W 充电器',
    '充电器',
    'POWERTRAVEL',
    399,
    0,
    ['140W PD 3.1', '双 USB-C', '可折叠'],
    '适配高功率设备的差旅选择，需核对设备协议。',
    'orange',
  ],
  [
    'p09',
    'LinkHub 6 合 1 扩展坞',
    '扩展坞',
    'LINKHUB',
    199,
    32,
    ['HDMI 4K@30Hz', 'PD 100W 输入', 'USB-C 连接'],
    '连接显示器、键鼠和存储设备，整理你的工作台。',
    'blue',
  ],
  [
    'p10',
    'LinkHub Pro 9 合 1 扩展坞',
    '扩展坞',
    'LINKHUB PRO',
    329,
    8,
    ['HDMI 4K@60Hz', '千兆网口', 'SD / TF'],
    '更丰富的接口，为多设备工作流而设计。',
    'purple',
  ],
  [
    'p11',
    'LinkGo 4 合 1 扩展坞',
    '扩展坞',
    'LINKGO',
    99,
    48,
    ['USB-A × 3', 'USB-C 数据口', '仅数据传输'],
    '轻便的数据接口扩展，不提供视频输出。',
    'mint',
  ],
  [
    'p12',
    'LinkStation 双屏扩展坞',
    '扩展坞',
    'LINKSTATION',
    599,
    0,
    ['双 HDMI', '独立供电', '需核对系统支持'],
    '为固定工位准备，双屏模式需核对设备和系统。',
    'orange',
  ],
];
export const products: Product[] = items.map(
  ([id, name, category, series, price, stock, specs, description, color]) => ({
    id,
    name,
    category,
    series,
    price,
    stock,
    specs,
    description,
    color,
    source: `KB-${id.toUpperCase()} · ${name}说明书 v1.0`,
  }),
);
export const orders: Order[] = [
  {
    id: '10001',
    buyer: 'A',
    productId: 'p01',
    quantity: 1,
    status: '运输中',
    date: '2026-09-14',
    logistics: [
      {
        time: '09-15 09:20',
        title: '运输中',
        detail: '快件已到达杭州转运中心，正在发往目的站点。',
      },
      { time: '09-14 18:35', title: '已揽收', detail: '演示速运已揽收包裹。' },
      { time: '09-14 15:10', title: '商家已发货', detail: '商品已出库，等待承运方揽收。' },
    ],
  },
  {
    id: '10002',
    buyer: 'A',
    productId: 'p02',
    quantity: 1,
    status: '已签收',
    date: '2026-09-10',
    logistics: [
      { time: '09-12 14:30', title: '已签收', detail: '包裹已签收。如有问题，可申请售后。' },
      { time: '09-11 10:00', title: '运输中', detail: '演示包裹正在运输。' },
    ],
  },
  {
    id: '10003',
    buyer: 'A',
    productId: 'p09',
    quantity: 1,
    status: '已完成',
    date: '2026-09-01',
    logistics: [{ time: '09-03 11:20', title: '已签收', detail: '历史订单已完成。' }],
  },
  {
    id: '10004',
    buyer: 'A',
    productId: 'p05',
    quantity: 2,
    status: '待发货',
    date: '2026-09-15',
    logistics: [],
  },
  {
    id: '20001',
    buyer: 'B',
    productId: 'p10',
    quantity: 1,
    status: '已签收',
    date: '2026-09-08',
    logistics: [{ time: '09-10 16:00', title: '已签收', detail: '演示订单已签收。' }],
  },
];
export const policies = [
  {
    id: 'POL-01',
    title: '发货与物流',
    content:
      '演示店铺有货商品通常在订单确认后 48 小时内安排发货。实际进度以订单和物流结果为准；没有预计送达信息时不作到货承诺。',
  },
  {
    id: 'POL-02',
    title: '售后申请与审核',
    content:
      '买家提供订单、商品和问题描述后可提交售后申请。所有申请由人工结合商品状态和问题审核；申请获批后按指引处理退件，不代表退款到账。本演示不执行真实退款。',
  },
  {
    id: 'POL-03',
    title: '兼容性与充电功率',
    content:
      '扩展坞的视频输出依赖主机端口支持视频输出协议；USB-C 外观不能证明支持。充电器实际功率由设备协议、线材和多口分配共同决定，购买前请核对设备型号及接口规格。',
  },
];
export const findProduct = (id: string) => products.find((p) => p.id === id)!;
export const findOrder = (id: string, buyer: BuyerId) =>
  orders.find((o) => o.id === id && o.buyer === buyer);
export const money = (n: number) => `¥${n.toLocaleString('zh-CN')}`;
export const quickQuestions = [
  '帮我推荐 300 元以内的耳机',
  '查询订单 10001 的物流',
  '订单 10002 耳机有一边没声音，想退货',
];
